version: '3'
services:
  app:
    build: .
    restart: always
    ports:
      - 10101:8080
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ou3QP7sP9q
    volumes:
      - mongo:/data/db
  rabbitmq:
    image: rabbitmq
    restart: always
volumes:
  mongo:
