version: '3'
services:
  app:
    build:
      context: .
    restart: always
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: p7uOsOyR1GhRfqD2xoY0BocRXkUBArug
    ports:
      - 10000:27017
    volumes:
      - mongo:/data/db
volumes:
  mongo:
