spring:
  data:
    mongodb:
      database: main
      host: mongo
      username: root
      password: ou3QP7sP9q
      authentication-database: admin
  rabbitmq:
    host: rabbitmq
    listener:
      simple:
        default-requeue-rejected: off
  servlet:
    multipart:
      max-file-size: 10MB
main:
  telegram-bot:
    username: FoodAnalysisBot
    token: 1039439731:AAEJfHiV8_tnApfg5cyazlgUT82LgqonMIw
