name: CD

on:
  push:
    branches: master

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: mvn clean install -DskipTests
      - name: deploy
        run: docker-compose up -d --build
