name: CD

on:
  push:
    branches: master

jobs:
  build:
    runs-on: self-hosted
    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      OCR_API_KEY: ${{ secrets.OCR_API_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: shut down app as we lack resources
        run: docker-compose down || exit 0
      - name: build
        run: mvn clean install -DskipTests
      - name: deploy
        run: docker-compose up -d --build
